project_id = "yasicaakzqqhmtgscbhg"

[functions.gemini-chat]
verify_jwt = false

[functions.generate-product]
verify_jwt = false

[functions.upload-image]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.analytics-insights]
verify_jwt = false

[functions.adminsuper-login]
verify_jwt = false
